version: 2
updates:
  # Enable version updates for pip dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
